### ISSUE TITLE
Why isn't this a fork?

### ISSUE THREAD

**Issue by michael-hawker** [phoenix-actions/test-reporting#9]
Curious why this fork was created without the original history of https://github.com/dorny/test-reporter? (If it's for issues, they should be able to be [enabled afterwards](https://softwareengineering.stackexchange.com/questions/179468/forking-a-repo-on-github-but-allowing-new-issues-on-the-fork).)

It'd be useful to be linked to the original project still and anyone who forked the original would have an easier time contributing here if the history and commits were linked/maintained.

It looks like the intent is to carry the project forward as the original repo hasn't had an update, but that's not clear based on the readme info.

Would be great to have some more background on the goals here as this does seem like a useful project. Thanks!

**Comment by IanMoroney** [comment]
@michael-hawker, good question! and thank you :)
No specific reason for not maintaining the history. It may have been my lack of knowledge of forking a repo into a new github org, instead of a personal project. That, and the need I had at the time to get it operational was time sensitive.
I thought I had a link back to the original repo in the readme, but it doesn't seem to be there so I'll add it.

The primary reason for the fork in the first place was a need, which was to support `mochawesome-json`, and I also noticed from the issue list on dorny's repo that issues and feature enhancements weren't getting done, so I took the best of the fixes and feature enhancements that users wanted and incorporated them into this!

I'll definitely update the readme to explain the reason why this exists. 👍 

I hope that answers your question!
